# Site settings
title: SpaceBound Minds
description: Online resources for the SpaceBound Minds workshop
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Spacebound Minds
user_description: Mission control have sorted out the basics — food, water, air — but the rest is up to you!
user_title: Mission control have sorted out the basics — food, water, air — but the rest is up to you!
email: someone@ed.ac.uk
# twitter_username: lorem_ipsum
# instagram_username: lorem_ipsum
# facebook_username: lorem_ipsum
# linkedin_username: lorem_ipsum
# github_username:  lorem_ipsum
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

